# Numpy

![Numpy](https://miro.medium.com/v2/resize:fit:765/0*L5DN6kQLvhvvw02U.png)

In [1]:
import numpy as np

# Basics Numpy

In [2]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[10,11,12], [13,14,15], [16,17,18], [19,20,21]]) 
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d = np.array([[[10,11,12,13],[13,14,15,6],[16,17,18,19]],[[19,20,21,22],[23,24,25,26],[27,28,29,30]]])
print("a =\n", a, "\n")
print("b =\n", b, "\n")
print("c =\n", c, "\n")
print("d =\n", d, "\n")
print("a shape =", a.shape, "(RowxColumn)")
print("b shape =", b.shape, "(RowxColumn)")
print("c shape =", c.shape, "(SetxRowxColumn)")
print("d shape =", d.shape, "(SetxRowxColumn)", "\n")
print("a size =", a.size, "(Row*Column)")
print("b size =", b.size, "(Row*Column)")
print("c size =", c.size, "(Set*Row*Column)")
print("d size =", d.size, "(Set*Row*Column)", "\n")
print("a datatype =", a.dtype)
print("b datatype =", b.dtype)
print("c datatype =", c.dtype)
print("d datatype =", d.dtype, "\n" )
print("a dimension =", a.ndim, "D")
print("b dimension =", b.ndim, "D")
print("c dimension =", c.ndim, "D")
print("d dimension =", d.ndim, "D")


a =
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

b =
 [[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] 

c =
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

d =
 [[[10 11 12 13]
  [13 14 15  6]
  [16 17 18 19]]

 [[19 20 21 22]
  [23 24 25 26]
  [27 28 29 30]]] 

a shape = (3, 3) (RowxColumn)
b shape = (4, 3) (RowxColumn)
c shape = (2, 2, 3) (SetxRowxColumn)
d shape = (2, 3, 4) (SetxRowxColumn) 

a size = 9 (Row*Column)
b size = 12 (Row*Column)
c size = 12 (Set*Row*Column)
d size = 24 (Set*Row*Column) 

a datatype = int32
b datatype = int32
c datatype = int32
d datatype = int32 

a dimension = 2 D
b dimension = 2 D
c dimension = 3 D
d dimension = 3 D


# NumpyArray VS List

In [3]:
List = [1,2,3,4]
NpArray = np.array([1,2,3,4])

print("List =", List)
print("NpArray =", NpArray, "\n")
print("+5\n")

List = List + [5]
NpArray = NpArray + [5]

print("List =", List, "(This one add the number 5 to member of the list)")
print("NpArray =", NpArray, "(This one add 5 to every member in the array)\n")
print("*2\n")

List = List*2
NpArray = NpArray*2

print("List =", List, "(This one repeat the list)")
print("NpArray =", NpArray, "(This one multiply 2 to every member in the array)\n")

List = [1, 2, 3, 4]
NpArray = [1 2 3 4] 

+5

List = [1, 2, 3, 4, 5] (This one add the number 5 to member of the list)
NpArray = [6 7 8 9] (This one add 5 to every member in the array)

*2

List = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] (This one repeat the list)
NpArray = [12 14 16 18] (This one multiply 2 to every member in the array)



# Dot product NumpyArray VS List

In [4]:
list1 = [1,2,3]
list2 = [4,5,6]

print("list1 =", list1)
print("list2 =", list2)

dot_list = 0

for i in range(len(list1)):
    dot_list = dot_list + list1[i]*list2[i]
print("dot_list =", dot_list, "(use for loop)\n")

a = np.array([1,2,3])
b = np.array([4,5,6])

print("array1 =", a)
print("array2 =", b)

dot_array = np.dot(a,b)
print("dot_array =", dot_array, "(use np.dot function)\n")

# another way to do dot in numpy array

dot_array2 = a*b
dot_array2 = np.sum(dot_array2)
print("dot_array2 =", dot_array2, "(element wise multiply and sum)\n")

# or

print("dot_array3 =", a@b, "(use @ to dot product)")

list1 = [1, 2, 3]
list2 = [4, 5, 6]
dot_list = 32 (use for loop)

array1 = [1 2 3]
array2 = [4 5 6]
dot_array = 32 (use np.dot function)

dot_array2 = 32 (element wise multiply and sum)

dot_array3 = 32 (use @ to dot product)


# Indexing, Slicing, Boolean Indexing

1 Dimension

In [5]:
a = np.array([1,2,3,4,5])
print("a =", a, "\n")

print("a[0] = ", a[0])
print("a[1] =", a[1])
print("a[2] =", a[2])
print("a[3] =", a[3])
print("a[4] =", a[4], "\n\n *** Index starting from 0 ***")

a = [1 2 3 4 5] 

a[0] =  1
a[1] = 2
a[2] = 3
a[3] = 4
a[4] = 5 

 *** Index starting from 0 ***


2 Dimension

In [6]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("b =\n", b, "\n")

print("b[0] =", b[0], "\nb[1] =", b[1], "\nb[2] =", b[2], "\n")
print("or\n")
print("b[0,:] =", b[0,:], "\nb[1,:] =", b[1,:], "\nb[2,:] =", b[2,:])
print("\nfirst number in the [] is Row and after , is Column\n: mean choose all")


b =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

b[0] = [1 2 3 4] 
b[1] = [5 6 7 8] 
b[2] = [ 9 10 11 12] 

or

b[0,:] = [1 2 3 4] 
b[1,:] = [5 6 7 8] 
b[2,:] = [ 9 10 11 12]

first number in the [] is Row and after , is Column
: mean choose all


In [7]:
print("b =\n", b, "\n")

print("b[:,0] =", b[:,0], "\nb[:,1] =", b[:,1], "\nb[:,2] =", b[:,2], "\n")
print("b[0,0] =", b[0,0])
print("b[2,1] =", b[2,1])
print("b[1,3] =", b[1,3])
print("\nfirst number in the [] is Row and after , is Column\n: mean choose all")

b =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

b[:,0] = [1 5 9] 
b[:,1] = [ 2  6 10] 
b[:,2] = [ 3  7 11] 

b[0,0] = 1
b[2,1] = 10
b[1,3] = 8

first number in the [] is Row and after , is Column
: mean choose all


In [8]:
print("indexing by - mean count from behind\n")
print("b =\n", b, "\n")

print("b[-1,-2] =", b[-1,-2])
print("b[-2,-1] =", b[-2,-1])
print("b[-1,-1] =", b[-1,-1])
print("b[-3,-4] =", b[-3,-4])

print("\n*** Indexing of - will start from -1 not 0 ***")

indexing by - mean count from behind

b =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

b[-1,-2] = 11
b[-2,-1] = 8
b[-1,-1] = 12
b[-3,-4] = 1

*** Indexing of - will start from -1 not 0 ***


Slicing 

[Row:Column:Step]

In [9]:
print("b =\n", b, "\n")

print("b Row1-2,Column1-3 =\n", b[0:2,0:3], "\n")
print("b Row2-3,Column2-4 =\n", b[1:3,1:4], "\n")
# or
print("b Row2-3,Column2-4 =\n", b[1:,1:])

b =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

b Row1-2,Column1-3 =
 [[1 2 3]
 [5 6 7]] 

b Row2-3,Column2-4 =
 [[ 6  7  8]
 [10 11 12]] 

b Row2-3,Column2-4 =
 [[ 6  7  8]
 [10 11 12]]


### Boolean Indexing

In [15]:
print("b =\n", b, "\n")

boolean = b > 5
print("b > 5 =\n", boolean, "\n")

boolean = b <= 5
print("b <= 5 =\n", boolean)

print("\nnow will print the element\n")

print("b <= 5 =\n", b[boolean], "\n")

# or

print("b <= 5 =\n", b[b <= 5], "\n")

# as you see it not the same size so you can do this

b = np.where(b <= 5, b, -1)
print("b <= 5 =\n", b)

#which one is flase from condition it will return -1

b =
 [ 2  4  6  8 10 12] 

b > 5 =
 [False False  True  True  True  True] 

b <= 5 =
 [ True  True False False False False]

now will print the element

b <= 5 =
 [2 4] 

b <= 5 =
 [2 4] 

b <= 5 =
 [ 2  4 -1 -1 -1 -1]


In [11]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("b =\n", b, "\n")

#flatten() is use to made matrix to 1 D

b = b.flatten()
print("b_flatten =", b, "\n")

even = np.argwhere(b % 2 == 0)
print("even =\n", even, "\n")

even = even.flatten()
print("even_flatten =",even, "\n")

b = b[even]
print("even_b =", b)

#this call fancy indexing pass an index you want to print to [] of array

b =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

b_flatten = [ 1  2  3  4  5  6  7  8  9 10 11 12] 

even =
 [[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]] 

even_flatten = [ 1  3  5  7  9 11] 

even_b = [ 2  4  6  8 10 12]


### Reshaping

In [12]:
c = np.array([[20,19,18,17],[16,15,14,13],[12,11,10,9]])
print("c =\n", c)
print("\nc shape =", c.shape, "\n")

#reshaping

c = c.reshape(2,6)
print("c_reshape =\n", c, "\n")

c = c.reshape(12,1)
print("c_reshape2 =\n", c, "\n")

c = c.reshape(4,3)
print("c_reshape3 =\n", c, "\n")

c = c.reshape(5,2)
print("c_reshape4 =\n", c)
#this one error because matrix size didn't match the old one the old one have 12 this one have 10

c =
 [[20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]]

c shape = (3, 4) 

c_reshape =
 [[20 19 18 17 16 15]
 [14 13 12 11 10  9]] 

c_reshape2 =
 [[20]
 [19]
 [18]
 [17]
 [16]
 [15]
 [14]
 [13]
 [12]
 [11]
 [10]
 [ 9]] 

c_reshape3 =
 [[20 19 18]
 [17 16 15]
 [14 13 12]
 [11 10  9]] 



ValueError: cannot reshape array of size 12 into shape (5,2)

### Random

In [37]:
# Random from 0-1
random0_1 = np.random.random((3, 2))

# Random Gaussian Distribution mean = 0, std = 1
random_gauss = np.random.randn(10)

# Random Integer 
random_int = np.random.randint(0, 10, size = (3,4))

# Random Choice
random_choice = np.random.choice([5,10,15,20], size = (4,3))

# Random Normal Distribution
random_normal = np.random.normal(loc = 18, scale = 4, size = 20)

print(f'random0_1 = \n{random0_1}\n')

print(f'random_gauss = \n{random_gauss}\n')

print(f'random_int = \n{random_int}\n')

print(f'random_choice = \n{random_choice}\n')

print(f'random_normal = \n{random_normal}')
print(f'\nmean = {random_normal.mean()}\nstd = {random_normal.std()}')

random0_1 = 
[[0.66328329 0.27190304]
 [0.28200101 0.47804655]
 [0.26635262 0.33341266]]

random_gauss = 
[ 0.29839852  1.32041866 -0.17734266 -0.90325355  1.75295393  0.28577295
  0.62743082  0.25556782 -0.0082521  -1.52275944]

random_int = 
[[7 1 8 3]
 [3 9 6 5]
 [2 5 2 1]]

random_choice = 
[[20  5 15]
 [10  5 20]
 [20 10  5]
 [ 5 20 10]]

random_normal = 
[12.0917113  16.32651805 13.22190377 19.50899562 18.37898814  8.82646764
 24.68215001 19.60124271 22.14632588 19.66958764 23.03835879 25.72292184
 19.88626397 14.61437536 14.78519913 13.17474445 15.54453085 17.45666765
 14.74553332 16.76138932]

mean = 17.509193772495742
std = 4.252100428563955
